numBatteryPacks=8

# RS485 properties
RS485.baudrate=9600
RS485.startFlag=165
RS485.frameLength=13
#bms.portname=com3
#bms.portname=/dev/ttyS0

# IO port properties
bms.portname=can0
inverter.portname=can0


#MQTT properties
mqtt.locator=tcp://127.0.0.1:61616
mqtt.topic=energystorage