numBatteryPacks=8

# RS485 properties
RS485.baudrate=9600
RS485.startFlag=165
RS485.frameLength=13


# ModBus properties
ModBus.baudrate=9600

# IO port properties
#bms.portname=com3
#bms.portname=/dev/ttyS0

# simple single port configuration
bms.portname=can0

# or for multiple BMSes connected to multiple ports 
#bms.0.portname=can0
#bms.1.portname=can1
#bms.2.portname=can2
#bms.3.portname=can3

inverter.portname=can1


#MQTT properties
mqtt.locator=tcp://127.0.0.1:61616
mqtt.topic=energystorage


# Email properties
mail.out.debug=true
mail.out.host=smtp.gmail.com
mail.out.port=587
# smtp for TLS, smtps for SSL
mail.out.type=smtp
mail.out.username=
mail.out.password=
# disable if using TLS
mail.out.sslEnable=false
# disable if using SSL
mail.out.tlsEnable=true
mail.out.defaultEmail=