numBatteryPacks=8

# RS485 properties
RS485.baudrate=9600
RS485.startFlag=165
RS485.frameLength=13


# ModBus properties
ModBus.baudrate=9600

# IO port properties
#bms.portname=com3
#bms.portname=/dev/ttyS0
bms.portname=can0
inverter.portname=can1


#MQTT properties
mqtt.locator=tcp://127.0.0.1:61616
mqtt.topic=energystorage